name: Generate chat bubble SVG

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Generate chat bubble SVG
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node generate-svg.js

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Daniel Arbesú
          author_email: daniel.arbesu.sanchez@gmail.com
          message: 'Update chat bubble with current date and weather'
          add: '*.svg'
